version: '3'

tasks:

  default:
    silent: true
    cmd: task --list

  dependencies:
    desc: Install dependencies specified in the Gemfile
    cmd: bundle install

  run:
    desc: Run website locally
    cmd: bundle exec jekyll serve
